
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: on-failure:10
    privileged: true
    hostname: 'localhost'
    configs:
      - source: gitlab_omnibus_config
        target: /opt/configs/omnibus_config.rb
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/opt/configs/omnibus_config.rb')"
      GITLAB_ROOT_PASSWORD:
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN:
      RAILS_ENV: production
    ports:
     - '80:80'
     - '443:443'
    volumes:
     - gitlab_git:/var/opt/gitlab/git-data:Z
     - gitlab_config:/etc/gitlab:Z
     - gitlab_logs:/var/log/gitlab:Z
     - gitlab_data:/var/opt/gitlab:Z
     - gitlab_backups:/var/opt/gitlab/backups:Z
    shm_size: '256m'
    depends_on:
      - db
    deploy:
      mode: global

  db:
    image: postgres:latest
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=gitlabhq_production
    ports:
     - 0.0.0.0:5432:5432

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner:/etc/gitlab-runner:Z
    deploy:
      mode: replicated
      replicas: 4

volumes:
  postgres_data:
  gitlab_data:
  gitlab_git:
  gitlab_config:
  gitlab_logs:
  gitlab_backups:
  gitlab_runner:

configs:
  gitlab_omnibus_config:
    file: ./configs/omnibus_config.rb
